api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
  dashboard:
    address: ":8080"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
