-- PeaceFestivalUSA Deployment Lessons: Windows Hosts File Management
-- This script inserts a critical lesson into the AgencyStack lessons database
-- Charter Principle: Repository as Source of Truth, Auditability, Cross-Platform Repeatability

INSERT INTO lessons (category_id, project_id, description)
VALUES (
    (SELECT id FROM categories WHERE name = 'Networking'),
    (SELECT id FROM projects WHERE name = 'PeaceFestivalUSA'),
    'For local development with custom domains (e.g., peacefestivalusa.localhost), the Windows hosts file must be edited to include:\n127.0.0.1 peacefestivalusa.localhost\n127.0.0.1 traefik.peacefestivalusa.localhost\nThis step cannot be fully automated from WSL/Linux due to OS boundaries and permissions. A helper script and README should be generated by the installer, and the user must run the script as Administrator and flush the DNS cache (ipconfig /flushdns) for changes to take effect. This ensures browser access to local services via custom domains and should be logged and documented for future deployments.'
);

-- Link to the relevant AgencyStack Charter Principle
INSERT INTO lesson_principles (lesson_id, principle_id)
VALUES (
    (SELECT id FROM lessons WHERE description LIKE '%Windows hosts file must be edited%'),
    (SELECT id FROM charter_principles WHERE name = 'Repository as Source of Truth')
);
